title = "Custom Gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Globale Ausnahmen"
paths = [
  '''(^|/)\.git/''',
  '''(^|/)node_modules/''',
  '''(^|/)dist/''',
  '''(^|/)build/''',
  '''(^|/)coverage/'''
]