-- manual assetlist
INSERT INTO stocks.assets (canonical_symbol, name, category)
VALUES
('AAPL','Apple','stock'),
('AMZN','Amazon','stock'),
('MSFT','Microsoft','stock'),
('TSLA','Tesla','stock'),
('NVDA','Nvidia','stock'),
('MRNA','Moderna','stock'),
('UL','Unilever','stock'),
('BMW','BMW','stock'),
('VOW3','Volkswagen','stock'),
('RHM','Rheinmetall','stock'),
('BAYN','Bayer','stock'),
('BAS','BASF','stock'),
('AML','Aston Martin','stock'),
('MBG','Mercedes-Benz','stock'),
('CWR','Ceres Power','stock'),
('SHA','Schaeffler','stock'),
('MNST','Monster Beverage','stock'),
('URTH','iShares MSCI World ETF','etf'),
('SPY','SPDR S&P 500 ETF','etf'),
('SPX','S&P 500 Index','index'),
('BTC','Bitcoin','crypto'),
('SOL','Solana','crypto'),
('DOGE','Dogecoin','crypto'),
('XAU','Gold','commodity'),
('XAG','Silver','commodity'),
('P911','Porsche AG','stock');


-- manual mapping of assets
INSERT INTO stocks.asset_symbols
(asset_id,provider,provider_symbol,exchange)
VALUES
-- Yahoo
(1,'yahoo','AAPL','NASDAQ'),
(2,'yahoo','AMZN','NASDAQ'),
(3,'yahoo','MSFT', 'NASDAQ'),
(4,'yahoo','TSLA', 'NASDAQ'),
(5,'yahoo','NVDA', 'NASDAQ'),
(6,'yahoo','MRNA', 'NASDAQ'),
(7,'yahoo','UL', 'NYSE'),
(8,'yahoo','BMW.DE', 'XETRA'),
(9,'yahoo','VOW3.DE', 'XETRA'),
(10,'yahoo','RHM.DE', 'XETRA'),
(11,'yahoo','BAYN.DE', 'XETRA'),
(12,'yahoo','BAS.DE', 'XETRA'),
(13,'yahoo','AML.L', 'LSE'),
(14,'yahoo','MBG.DE', 'XETRA'),
(15,'yahoo','CWR.L', 'LSE'),
(16,'yahoo','SHA.DE', 'XETRA'),
(17,'yahoo','MNST','NASDAQ'),
(18,'yahoo','URTH','NYSEARCA'),
(19,'yahoo','SPY','NYSEARCA'),
(20,'yahoo','^GSPC','INDEX'),
(21,'yahoo','BTC','CRYPTO'),
(22,'yahoo','SOL','CRYPTO'),
(23,'yahoo','DOGE','CRYPTO'),
(24,'yahoo','XAU','COMMODITY'),
(25,'yahoo','XAG','COMMODITY'),
(26,'yahoo','P911.DE','XETRA'),

-- Polygon
(1,'polygon','AAPL', 'NASDAQ'),
(2,'polygon','AMZN', 'NASDAQ'),
(3,'polygon','MSFT', 'NASDAQ'),
(4,'polygon','TSLA', 'NASDAQ'),
(5,'polygon','NVDA', 'NASDAQ'),
(6,'polygon','MRNA', 'NASDAQ'),
(7,'polygon','UL', 'NYSE'),
(8,'polygon','XETRA:BMW', 'XETRA'),
(9,'polygon','XETRA:VOW3', 'XETRA'),
(10,'polygon','XETRA:RHM', 'XETRA'),
(11,'polygon','XETRA:BAYN', 'XETRA'),
(12,'polygon','XETRA:BAS', 'XETRA'),
(13,'polygon','LSE:AML', 'LSE'),
(14,'polygon','XETRA:MBG', 'XETRA'),
(15,'polygon','LSE:CWR', 'LSE'),
(16,'polygon','XETRA:SHA', 'XETRA'),
(17,'polygon','MNST','NASDAQ'),
(18,'polygon','URTH','NYSEARCA'),
(19,'polygon','SPY','NYSEARCA'),
(20,'polygon','I:SPX','INDEX'),
(21,'polygon','X:BTCUSD','CRYPTO'),
(22,'polygon','X:SOLUSD','CRYPTO'),
(23,'polygon','X:DOGEUSD','CRYPTO'),
(24,'polygon','C:XAUUSD','COMMODITY'),
(25,'polygon','C:XAGUSD','COMMODITY'),
(26,'polygon','XETRA:P911','XETRA');